// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHBCwwC8-G_H9VfQClCKShTisuy9u0qJA',
    appId: '1:414038496032:web:917a647105207b2fc93d45',
    messagingSenderId: '414038496032',
    projectId: 'whats-for-dino',
    authDomain: 'whats-for-dino.firebaseapp.com',
    storageBucket: 'whats-for-dino.firebasestorage.app',
    measurementId: 'G-9TY6MMW8GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5bwIpVWoSq8gwAhjIm7tVc-VbQ194xsk',
    appId: '1:414038496032:android:367eb647acfadd46c93d45',
    messagingSenderId: '414038496032',
    projectId: 'whats-for-dino',
    storageBucket: 'whats-for-dino.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU1OLZixwfcpqqee2yAu0J2lRK_-c1APs',
    appId: '1:414038496032:ios:660bb6840a5eaa08c93d45',
    messagingSenderId: '414038496032',
    projectId: 'whats-for-dino',
    storageBucket: 'whats-for-dino.firebasestorage.app',
    iosBundleId: 'com.example.whatsForDino2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU1OLZixwfcpqqee2yAu0J2lRK_-c1APs',
    appId: '1:414038496032:ios:660bb6840a5eaa08c93d45',
    messagingSenderId: '414038496032',
    projectId: 'whats-for-dino',
    storageBucket: 'whats-for-dino.firebasestorage.app',
    iosBundleId: 'com.example.whatsForDino2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHBCwwC8-G_H9VfQClCKShTisuy9u0qJA',
    appId: '1:414038496032:web:7c53eb10259600ffc93d45',
    messagingSenderId: '414038496032',
    projectId: 'whats-for-dino',
    authDomain: 'whats-for-dino.firebaseapp.com',
    storageBucket: 'whats-for-dino.firebasestorage.app',
    measurementId: 'G-FLBZNY72HC',
  );
}
